### ISSUE TITLE
SSL certificate and HTTPS protocol for OpenVPNAdmin

### ISSUE THREAD

**Issue by karabelnikov** [bnhf/pivpn-tap-web-ui#36]
**@bnhf** 

Scott, I would like to touch on another important topic when using the OpenVPN Admin project in production. This is a connection to the web interface via an SSL certificate using an HTTPS connection. How difficult is it to implement in a container? Many use their own certificate authority to issue certificates for use in the organization projects, such as OpenVPN Admin.

**Comment by bnhf** [comment]
@karabelnikov 

This would not be difficult to implement, either as a code change, or by updating the app.conf file, as referenced in this PR from the original project: https://github.com/adamwalach/openvpn-web-ui/pull/9

The app.conf change seems like the way to go, but I don't know much about the whole certificate generation process. We'd want users to have a self-signed certificate initially, with the ability to get a "real" certificate I would think -- but as I say I'm not really tuned-in to this process.

Personally, I would continue to use http since I only use the interface on my local network or over a VPN. The other reason I use http for most of my internal server stuff is Organizr, which I love, particularly when my various WebUIs work in iFrames. I've been known to go to some lengths to disable https, for this very reason. :-)

**Comment by bnhf** [comment]
@karabelnikov 

Oh, and one other thing worth mentioning:

If you notice in the comment attached to the PR, the path for the certificates has "dehydrated" in it, which I'm sure refers to this project: https://github.com/dehydrated-io/dehydrated

**Comment by karabelnikov** [comment]
**@bnhf** 

My suggestion is to use the code editing path. HTTPS should be an alternative to HTTP, but not a complete replacement. I threw some thoughts, I think you get the point. This is how I see it:

```
beego.BConfig.Listen.EnableHTTPS = true
beego.BConfig.Listen.HTTPSPort = 8443
beego.BConfig.Listen.HTTPSCertFile = "$PatchSSLFolder" + "$NameSSLCert"
beego.BConfig.Listen.HTTPSKeyFile =  "$PatchSSLFolder" + "$NameSSLKey"

$PatchSSLFolder = "/etc/openvpn/ssl/"
$NameSSLCert = "name.crt"
$NameSSLKey = "name.key"
```

**Comment by karabelnikov** [comment]
Something like that. So far this is just an idea. If the server needs an HTTPS protocol, it does everything I described above. If not needed, does nothing and uses HTTP

![Снимок экрана 2022-12-16 031909](https://user-images.githubusercontent.com/11692792/207979353-07dd95c3-c39d-4302-a14d-2e0ebf9d05f4.png)

**Comment by karabelnikov** [comment]
**This is how you create folders:**

package main
 
import (
	"os"
)

func main() {
 
	err = os.MkdirAll("openvpn-admin/ssl", 0777)
	if err != nil {
		panic(err)
	}
 
}

**Comment by karabelnikov** [comment]
![Снимок экрана 2022-12-16 в 12 54 42](https://user-images.githubusercontent.com/11692792/208056370-3b50dc10-f7b5-4424-9948-fb3f0e21d13a.png)

**Comment by bnhf** [comment]
@karabelnikov 

I've added support for https, including the optional use of a custom certificate and key. You'll need to use a custom docker-compose to test it until we determine that it's ready for prime time:
```yml
version: '3'
services:
  gui:
    image: bnhf/pivpn-tap-web-ui:beta
    container_name: openvpn-gui-tap
    environment:
      - OPENVPN_ADMIN_USERNAME=admin
      - OPENVPN_ADMIN_PASSWORD=b3secure
      - COUNTRY=${COUNTRY}
      - PROVINCE=${PROVINCE}
      - CITY=${CITY}
      - ORG=${ORG}
      - EMAIL=${EMAIL}
      - OU=${OU}
      - PIVPN_SERVER=${PIVPN_SERVER}
      - PIVPN_CONF=${PIVPN_CONF}
      - TZ=${TZ}
      - ENABLEHTTPS=${ENABLEHTTPS} # Optional (default=false)
      - HTTPSPORT=${HTTPSPORT} # Optional (default=8443)
      - HTTPSCERT=${HTTPSCERT} # Optional (default=/etc/openvpn/easy-rsa/pki/issued/${PIVPN_SERVER}.crt
      - HTTPSKEY=${HTTPSKEY} # Optional (default=/etc/openvpn/easy-rsa/pki/private/${PIVPN_SERVER}.key
    ports:
       - "8080:8080/tcp"
       - "8443:8443/tcp" # Optional (required if ENABLEHTTPS=true)
    restart: always
    volumes:
       - /etc/openvpn:/etc/openvpn
       - ./openvpn-data/db:/opt/openvpn-gui-tap/db
```

Then, of course, you'd need to actually supply the environment variables in that section of the Portainer Stack.
