### ISSUE TITLE
Revoke a valid certificate

### ISSUE THREAD

**Issue by karabelnikov** [bnhf/pivpn-tap-web-ui#7]
@bnhf

Friend, I know that this option has not been implemented yet, and this is part of your plans. Tell me, do you have an approximate timeline for the implementation of this function? I would like to switch completely to working with the web interface and refuse to work with the script for issuing and revoking certificates. Now I have configured the productive to work with OpenVPN of my scripts, everything works fine.

I have technical experience and a bit of development experience, maybe I could help with something? In the screenshot I showed this functionality. As far as I understand, you need to make the same section as for issuing the certificate, and screw in the certificate revocation script there, in the same way as for issuing the certificate.

![Снимок экрана 2022-12-05 в 13 01 12](https://user-images.githubusercontent.com/11692792/205611123-0c485574-90ab-40f8-a2dd-698cadf9a346.png)

**Comment by bnhf** [comment]
@karabelnikov 

Is the screenshot you sent me from another fork of the original openvpn-web-ui project? If so, which fork? I like this approach for revocation.

**Comment by karabelnikov** [comment]
**@bnhf** 

This is not a fork, it's just a bit of my imagination and a couple of actions in the web browser inspector :)) 😎
In fact, it's not difficult to implement, you need to add the same html block as for issuing the certificate, make a script for verification and bind it to the action of the **revocation button** with the variable "**name**" in the field.
And it will work.

**Comment by bnhf** [comment]
@karabelnikov 

I've implemented a certificate revocation and removal capability in OpenVPNAdmin. Give it a try when you have a chance. I'll include a suggested Docker compose below, as you won't be able to pull it using the Github method. Make sure you supply the required environment variables at the bottom of your Portainer Stack as well.

![Screenshot 2022-12-06 151212](https://user-images.githubusercontent.com/41088895/206035287-757b5b3b-37ab-4644-85b0-1dd66b6a925c.png)

```yml
version: '3'
services:
  gui:
    image: bnhf/pivpn-tap-web-ui:beta
    container_name: openvpn-gui-tap
    environment:
    - OPENVPN_ADMIN_USERNAME=admin
    - OPENVPN_ADMIN_PASSWORD=b3secure
    - COUNTRY=${COUNTRY}
    - PROVINCE=${PROVINCE}
    - CITY=${CITY}
    - ORG=${ORG}
    - EMAIL=${EMAIL}
    - OU=${OU}
    - PIVPN_SERVER=${PIVPN_SERVER}
    - PIVPN_CONF=${PIVPN_CONF}
    - TZ=${TZ}
    ports:
     - "8080:8080/tcp"
    restart: always
    volumes:
     - /etc/openvpn:/etc/openvpn
     - ./openvpn-data/db:/opt/openvpn-gui-tap/db
```
